import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Home/Navbar";
import Footer from "./Home/Footer";
import SmoothScroll from "@/components/SmoothScroll";
import ScrollToTop from "./Home/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Scholara",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="dm">
          <Navbar />
          <main>
            <SmoothScroll>
              {children}
              <Footer />
            </SmoothScroll>
          </main>
          <ScrollToTop />
        </div>
      </body>
    </html>
  );
}
